database_type:
  type: string
  displayName: Database
  default: Postgres
  options:
    - MySQL
    - Postgres
    - SQL Server
programming_language:
  type: string
  displayName: Language
  default: Python
  options:
    - JavaScript
    - Python
    - Java
    - Ruby
    - Go
operating_system:
  type: string
  displayName: OS
  default: macOS
  options:
    - Linux
    - macOS
    - Windows
favorite_color:
  displayName: Favorite color
  type: string
  default: blue
  options:
    - red
    - green
    - blue
    - yellow
    - orange
    - purple
