baseURL: 'http://localhost:1313/'
timeout: 100000
enableGitInfo: true

# Comment out locally to build all languages
renderSegments:
  - english

# Exclude all non-English languages
segments:
  english:
    includes:
    - lang: en