# TODO: This file is not in use yet, it will be used to
# protect the consistency of sitewide pref IDs 
# from page to page.
sitewide_pref_ids:
  - id: host
    display_name: Host
  - id: programming_lang
    display_name: Language
  - id: database
    display_name: Database
  - id: os
    display_name: Operating System
  - id: package_manager
    display_name: Package Manager