blue_item_options:
  - display_name: Ocean
    identifier: ocean
    default: true
  - display_name: Sky
    identifier: sky
  - display_name: Jeans
    identifier: jeans
  - display_name: Blueberry
    identifier: blueberry