red_item_options:
  - display_name: Ruby
    id: ruby
    default: true
  - display_name: Apple
    id: apple
  - display_name: Firetruck
    id: firetruck
  - display_name: Stop sign
    id: stop_sign